name: 'Check Pull Request Comments'
author: 'amine-arb-2019'
inputs:
  string-list:
    description: 'List of string to be checked in comment body'
    required: true    
runs:
  using: "node12"
  main: "index.js"